# Dataset 7 — Scheme Performance: Data Cleaning

## Objective
Inspect and clean mutual fund scheme performance data to prepare it for reliable analysis.

## Source
`data/raw/07_scheme_performance.csv`

## Output
`data/processed/cleaned_scheme_performance.csv`

## Workflow
1. Load and inspect the dataset.
2. Check data types and missing values.
3. Identify duplicate records.
4. Validate numeric values and performance metrics.
5. Apply appropriate cleaning steps.
6. Validate and export the cleaned dataset.

In [1]:
import pandas as pd
from pathlib import Path

# Define the project directory
project_path = Path.cwd().parent

# Load the raw scheme performance dataset
scheme_file = (
    project_path / "data" / "raw" / "07_scheme_performance.csv"
)

scheme_df = pd.read_csv(scheme_file)

print("Dataset loaded successfully!")
print("Dataset shape:", scheme_df.shape)

print("\nColumn names:")
print(scheme_df.columns.tolist())

print("\nData types:")
print(scheme_df.dtypes)

print("\nFirst five rows:")
display(scheme_df.head())

Dataset loaded successfully!
Dataset shape: (40, 19)

Column names:
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

Data types:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

First five rows:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [2]:
# Check missing values in each column
print("Missing values by column:")
print(scheme_df.isnull().sum())

# Check total missing values
print("\nTotal missing values:", scheme_df.isnull().sum().sum())

# Check duplicate rows
print("\nDuplicate rows:", scheme_df.duplicated().sum())

# Check duplicate AMFI codes
print(
    "Duplicate AMFI codes:",
    scheme_df["amfi_code"].duplicated().sum()
)

# Check unique values in important categorical columns
for col in ["fund_house", "category", "plan", "risk_grade"]:
    print(f"\nUnique values in {col}:")
    print(scheme_df[col].value_counts(dropna=False))

# Display rows with missing values
print("\nRows containing missing values:")
display(scheme_df[scheme_df.isnull().any(axis=1)])

Missing values by column:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Total missing values: 0

Duplicate rows: 0
Duplicate AMFI codes: 0

Unique values in fund_house:
fund_house
SBI Mutual Fund             5
HDFC Mutual Fund            5
ICICI Prudential MF         5
Nippon India MF             5
Kotak Mahindra MF           4
Axis Mutual Fund            4
Aditya Birla Sun Life MF    3
UTI Mutual Fund             3
Mirae Asset MF              3
DSP Mutual Fund             3
Name: count, dtype: int64

Unique values in category:
category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Short Duration      1
Value               1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

Unique values in plan:
plan
Regular    32
Direct      8
Name: count, dtype: int64

Unique values in risk_grade:
risk_grade
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

Rows containing missing values:

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [3]:
# Check for empty or whitespace-only strings
print("Empty strings by column:")

for col in scheme_df.select_dtypes(include=["object", "str"]).columns:
    empty_count = (
        scheme_df[col]
        .astype("string")
        .str.strip()
        .eq("")
        .sum()
    )

    if empty_count > 0:
        print(f"{col}: {empty_count}")

# Inspect the scheme with AMFI code 119598
print("\nInspecting scheme with AMFI code 119598:")

display(
    scheme_df.loc[
        scheme_df["amfi_code"] == 119598
    ].T
)

Empty strings by column:

Inspecting scheme with AMFI code 119598:

                                                             2
amfi_code                                               119598
scheme_name         SBI Small Cap Fund - Regular Plan - Growth
fund_house                                     SBI Mutual Fund
category                                             Small Cap
plan                                                   Regular
return_1yr_pct                                           24.56
return_3yr_pct                                           23.39
return_5yr_pct                                           20.67
benchmark_3yr_pct                                        22.16
alpha                                                     1.23
beta                                                      0.89
sharpe_ratio                                              0.94
sortino_ratio                                             1.35
std_dev_ann_pct                                           25.0
max_drawdown_pct                                        -13.35
aum_crore                                                19259
expense_ratio_pct                                         1.43
morningstar_rating                                           5
risk_grade                                           Very High

In [4]:
# Review descriptive statistics for numeric columns
print("Numeric column summary:")
display(scheme_df.describe().T)

# Check for infinite values
import numpy as np

numeric_df = scheme_df.select_dtypes(include="number")

print("\nInfinite values by column:")
print(
    pd.Series(
        np.isinf(numeric_df).sum(),
        index=numeric_df.columns
    )
)

# Check important value ranges
print("\nUnique Morningstar ratings:")
print(sorted(scheme_df["morningstar_rating"].unique()))

print("\nUnique risk grades:")
print(sorted(scheme_df["risk_grade"].unique()))

print("\nPlan values:")
print(sorted(scheme_df["plan"].unique()))

Numeric column summary:

,count,mean,std,min,25%,50%,75%,max
amfi_code,40.0,120247.00000,14534.998667,100016.00,118632.7500,119551.500,120842.2500,149324.00
return_1yr_pct,40.0,14.37600,4.883023,4.26,11.7350,14.620,16.3925,24.93
return_3yr_pct,40.0,14.08900,4.617253,5.14,12.0350,14.205,15.8825,23.39
return_5yr_pct,40.0,14.51675,4.454021,5.43,12.3400,14.185,17.5850,23.80
benchmark_3yr_pct,40.0,12.83550,4.740972,3.96,10.6900,13.090,14.7750,22.16
alpha,40.0,1.25350,0.447412,0.51,0.8875,1.205,1.7000,1.98
beta,40.0,0.87325,0.224846,0.22,0.8900,0.960,1.0000,1.04
sharpe_ratio,40.0,1.36175,1.475805,0.80,0.8650,0.925,0.9850,7.68
sortino_ratio,40.0,2.08250,2.203144,1.03,1.2700,1.445,1.6375,10.37
std_dev_ann_pct,40.0,14.96250,6.669282,0.50,14.0000,14.000,19.0000,25.00
max_drawdown_pct,40.0,-19.20025,8.819164,-33.50,-25.0625,-20.600,-14.2550,-2.23
aum_crore,40.0,26091.60000,13809.111340,979.00,17400.5000,26713.000,38125.0000,49046.00
expense_ratio_pct,40.0,1.23700,0.386584,0.55,0.7875,1.425,1.5400,1.64
morningstar_rating,40.0,4.25000,0.742484,3.00,4.0000,4.000,5.0000,5.00

Infinite values by column:
amfi_code             0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
dtype: int64

Unique Morningstar ratings:
[np.int64(3), np.int64(4), np.int64(5)]

Unique risk grades:
['High', 'Low', 'Moderate', 'Moderately High', 'Very High']

Plan values:
['Direct', 'Regular']

In [5]:
# Identify schemes with unusually high Sharpe and Sortino ratios
print("Schemes with Sharpe ratio above 2:")

display(
    scheme_df.loc[
        scheme_df["sharpe_ratio"] > 2,
        [
            "amfi_code",
            "scheme_name",
            "category",
            "sharpe_ratio",
            "sortino_ratio",
            "return_3yr_pct",
            "benchmark_3yr_pct",
        ],
    ]
)

print("\nSchemes with Sortino ratio above 3:")

display(
    scheme_df.loc[
        scheme_df["sortino_ratio"] > 3,
        [
            "amfi_code",
            "scheme_name",
            "category",
            "sharpe_ratio",
            "sortino_ratio",
            "return_3yr_pct",
            "benchmark_3yr_pct",
        ],
    ]
)

# Check whether percentage-based metrics have unexpected signs
print("\nNegative expense ratios:", (scheme_df["expense_ratio_pct"] < 0).sum())
print("Negative AUM values:", (scheme_df["aum_crore"] < 0).sum())
print("Non-positive beta values:", (scheme_df["beta"] <= 0).sum())

print(
    "Morningstar ratings outside 1–5:",
    (~scheme_df["morningstar_rating"].between(1, 5)).sum()
)

Schemes with Sharpe ratio above 2:

,amfi_code,scheme_name,category,sharpe_ratio,sortino_ratio,return_3yr_pct,benchmark_3yr_pct
14,120507,ICICI Pru Liquid Fund - Regular - Growth,Liquid,7.68,10.37,7.68,5.83
23,120844,Kotak Liquid Fund - Regular - Growth,Liquid,6.18,9.70,6.18,4.66
30,101208,ABSL Liquid Fund - Regular - Growth,Liquid,5.14,8.76,5.14,3.96

Schemes with Sortino ratio above 3:

,amfi_code,scheme_name,category,sharpe_ratio,sortino_ratio,return_3yr_pct,benchmark_3yr_pct
14,120507,ICICI Pru Liquid Fund - Regular - Growth,Liquid,7.68,10.37,7.68,5.83
23,120844,Kotak Liquid Fund - Regular - Growth,Liquid,6.18,9.70,6.18,4.66
30,101208,ABSL Liquid Fund - Regular - Growth,Liquid,5.14,8.76,5.14,3.96

Negative expense ratios: 0
Negative AUM values: 0
Non-positive beta values: 0
Morningstar ratings outside 1–5: 0

In [6]:
# Check duplicate scheme identifiers
print("Duplicate AMFI codes:", scheme_df["amfi_code"].duplicated().sum())

# Check duplicate scheme names
print("Duplicate scheme names:", scheme_df["scheme_name"].duplicated().sum())

# Check duplicate scheme-name and plan combinations
print(
    "Duplicate scheme-name and plan combinations:",
    scheme_df.duplicated(subset=["scheme_name", "plan"]).sum()
)

# Check data types
print("\nColumn data types:")
print(scheme_df.dtypes)

# Review scheme counts by category and plan
print("\nSchemes by category:")
print(scheme_df["category"].value_counts())

print("\nSchemes by plan:")
print(scheme_df["plan"].value_counts())

Duplicate AMFI codes: 0
Duplicate scheme names: 0
Duplicate scheme-name and plan combinations: 0

Column data types:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

Schemes by category:
category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Short Duration      1
Value               1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

Schemes by plan:
plan
Regular    32
Direct      8
Name: count, dtype: int64

In [7]:
# Create a separate copy for cleaning
cleaned_scheme_df = scheme_df.copy()

# Remove leading and trailing whitespace from text columns
text_columns = cleaned_scheme_df.select_dtypes(
    include=["object", "str"]
).columns

for col in text_columns:
    cleaned_scheme_df[col] = cleaned_scheme_df[col].str.strip()

# Verify the cleaned dataset
print("Original shape:", scheme_df.shape)
print("Cleaned shape:", cleaned_scheme_df.shape)
print("Missing values:", cleaned_scheme_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_scheme_df.duplicated().sum())

display(cleaned_scheme_df.head())

Original shape: (40, 19)
Cleaned shape: (40, 19)
Missing values: 0
Duplicate rows: 0

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [8]:
# Inspect the SBI Magnum Gilt Fund row
gilt_row = cleaned_scheme_df.loc[
    cleaned_scheme_df["amfi_code"] == 119120
]

display(gilt_row.T)

print("\nMissing values in this row:")
print(gilt_row.isnull().sum())

print("\nMissing values in the entire cleaned dataset:")
print(cleaned_scheme_df.isnull().sum())

                                                               4
amfi_code                                                 119120
scheme_name         SBI Magnum Gilt Fund - Regular Plan - Growth
fund_house                                       SBI Mutual Fund
category                                                    Gilt
plan                                                     Regular
return_1yr_pct                                              5.34
return_3yr_pct                                              6.07
return_5yr_pct                                              5.43
benchmark_3yr_pct                                           4.47
alpha                                                        1.6
beta                                                        0.22
sharpe_ratio                                                1.52
sortino_ratio                                               2.11
std_dev_ann_pct                                              4.0
max_drawdown_pct                                            -2.3
aum_crore                                                  24101
expense_ratio_pct                                           0.77
morningstar_rating                                             5
risk_grade                                                   Low

Missing values in this row:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Missing values in the entire cleaned dataset:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [9]:
# Define the output path
output_file = (
    project_path
    / "data"
    / "processed"
    / "cleaned_scheme_performance.csv"
)

# Export the cleaned dataset
cleaned_scheme_df.to_csv(output_file, index=False)

print("Dataset exported successfully!")
print("Saved to:", output_file)
print("Final shape:", cleaned_scheme_df.shape)

Dataset exported successfully!
Saved to: d:\Mutual-Fund-Analytics\data\processed\cleaned_scheme_performance.csv
Final shape: (40, 19)

In [10]:
# Reload the exported CSV
verified_df = pd.read_csv(output_file)

# Verify the exported dataset
print("Export verification successful!")
print("File exists:", output_file.exists())
print("Exported shape:", verified_df.shape)
print("Missing values:", verified_df.isnull().sum().sum())
print("Duplicate rows:", verified_df.duplicated().sum())

# Confirm the expected columns
print("\nColumn count:", len(verified_df.columns))
print("Columns match:", verified_df.columns.tolist() == cleaned_scheme_df.columns.tolist())

Export verification successful!
File exists: True
Exported shape: (40, 19)
Missing values: 0
Duplicate rows: 0

Column count: 19
Columns match: True

# ✅ Dataset 7: Scheme Performance — Cleaning Summary

## 📌 Dataset Overview
- **Source File:** `07_scheme_performance.csv`
- **Output File:** `data/processed/cleaned_scheme_performance.csv`
- **Original Shape:** 40 rows × 19 columns
- **Final Shape:** 40 rows × 19 columns

## 🧹 Data Cleaning Performed
- Loaded the raw scheme performance dataset using Pandas.
- Checked for missing values and duplicate records.
- Verified duplicate AMFI codes, scheme names, and scheme-name/plan combinations.
- Inspected numeric columns for invalid values and potential anomalies.
- Checked for invalid expense ratios, AUM values, beta values, and Morningstar ratings.
- Trimmed leading and trailing whitespace from text columns.
- Preserved potentially unusual financial metrics without unsupported modifications.

## 🔍 Data Quality Results
- **Missing Values:** 0
- **Duplicate Rows:** 0
- **Duplicate AMFI Codes:** 0
- **Duplicate Scheme Names:** 0
- **Duplicate Scheme-Name/Plan Combinations:** 0
- **Text Columns:** Trimmed

## 📊 Dataset Contents
The dataset contains scheme-level information covering:
- Scheme identification and fund house
- Mutual fund category and plan type
- 1-year, 3-year, and 5-year returns
- Benchmark returns, alpha, and beta
- Sharpe ratio and Sortino ratio
- Annualized standard deviation and maximum drawdown
- Assets under management (AUM)
- Expense ratio, Morningstar rating, and risk grade

## 💾 Export and Verification
- Exported the cleaned dataset to CSV format.
- Reloaded the exported file for verification.
- Checked the exported shape, missing values, duplicate rows, and column consistency.

## 🏁 Final Status
**Dataset 7 cleaning and export completed.**

The cleaned dataset is ready for subsequent analysis, subject to any additional validation required by the project.