# Dataset 9: Portfolio Holdings — Data Cleaning

## Objective

Load, inspect, and clean the mutual fund portfolio holdings dataset while preserving the original data.

## Source File

`data/raw/09_portfolio_holdings.csv`

## Output File

`data/processed/cleaned_portfolio_holdings.csv`

## Workflow

1. Load and inspect the dataset.
2. Check data types and missing values.
3. Identify duplicate records and formatting issues.
4. Validate numeric values and portfolio-related fields.
5. Apply appropriate cleaning steps.
6. Export and verify the cleaned dataset.

In [1]:
# Step 2: Load and inspect portfolio holdings

import pandas as pd
from pathlib import Path

project_path = Path.cwd().parent

input_file = (
    project_path / "data" / "raw" / "09_portfolio_holdings.csv"
)

holdings_df = pd.read_csv(input_file)

print("Dataset loaded successfully!")
print("Dataset shape:", holdings_df.shape)

print("\nColumn names:")
print(holdings_df.columns.tolist())

print("\nData types:")
print(holdings_df.dtypes)

print("\nFirst 5 rows:")
display(holdings_df.head())

Dataset loaded successfully!
Dataset shape: (322, 8)

Column names:
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

Data types:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

First 5 rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [2]:
# Step 3: Initial data quality checks

print("Missing values by column:")
print(holdings_df.isna().sum())

print("\nTotal missing values:", holdings_df.isna().sum().sum())

print("\nDuplicate rows:", holdings_df.duplicated().sum())

print("\nEmpty or whitespace-only text values:")
text_columns = holdings_df.select_dtypes(include="str").columns

for col in text_columns:
    empty_count = holdings_df[col].str.strip().eq("").sum()
    print(f"{col}: {empty_count}")

print("\nFirst 10 rows:")
display(holdings_df.head(10))

print("\nNumeric summary:")
display(holdings_df.describe())

Missing values by column:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Total missing values: 0

Duplicate rows: 0

Empty or whitespace-only text values:
stock_symbol: 0
stock_name: 0
sector: 0
portfolio_date: 0

First 10 rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31
5,119551,NTPC,NTPC Ltd,Utilities,7.48,897.70,2913.66,2025-12-31
6,119551,DIVISLAB,Divi's Laboratories,Pharma,3.21,286.44,3964.01,2025-12-31
7,119551,BHARTIARTL,Bharti Airtel Ltd,Telecom,13.94,452.19,5013.45,2025-12-31
8,119551,HCLTECH,HCL Technologies Ltd,IT,18.22,177.35,6024.13,2025-12-31
9,119551,MARUTI,Maruti Suzuki India Ltd,Automobile,7.20,1982.33,5461.85,2025-12-31

Numeric summary:

           amfi_code  weight_pct  market_value_cr  current_price_inr
count     322.000000  322.000000       322.000000         322.000000
mean   121210.434783   10.558975      1008.846646        4080.870528
std     14669.377920    6.060137       543.827535        2265.186353
min    100016.000000    0.990000        55.740000         246.780000
25%    118633.000000    6.015000       513.702500        2081.985000
50%    119552.000000    9.395000      1045.670000        4138.995000
75%    120842.750000   13.917500      1477.502500        5914.307500
max    149324.000000   38.180000      1999.500000        7942.960000

In [3]:
# Step 4: Validate numeric values and portfolio dates

numeric_columns = [
    "weight_pct",
    "market_value_cr",
    "current_price_inr",
]

print("Non-positive values:")
for col in numeric_columns:
    print(f"{col}: {(holdings_df[col] <= 0).sum()}")

print("\nPortfolio weight summary:")
display(holdings_df["weight_pct"].describe())

print("\nPortfolio dates:")
print("Invalid dates:", pd.to_datetime(
    holdings_df["portfolio_date"], errors="coerce"
).isna().sum())

print("Earliest date:", holdings_df["portfolio_date"].min())
print("Latest date:", holdings_df["portfolio_date"].max())

print("\nUnique portfolio dates:")
print(holdings_df["portfolio_date"].nunique())

print("\nUnique AMFI codes:", holdings_df["amfi_code"].nunique())
print("Unique stock symbols:", holdings_df["stock_symbol"].nunique())
print("Unique stock names:", holdings_df["stock_name"].nunique())

print("\nSector distribution:")
print(holdings_df["sector"].value_counts())

Non-positive values:
weight_pct: 0
market_value_cr: 0
current_price_inr: 0

Portfolio weight summary:

count    322.000000
mean      10.558975
std        6.060137
min        0.990000
25%        6.015000
50%        9.395000
75%       13.917500
max       38.180000
Name: weight_pct, dtype: float64

Portfolio dates:
Invalid dates: 0
Earliest date: 2025-12-31
Latest date: 2025-12-31

Unique portfolio dates:
1

Unique AMFI codes: 34
Unique stock symbols: 30
Unique stock names: 30

Sector distribution:
sector
Banking           60
IT                40
Pharma            38
Automobile        33
Utilities         24
Infrastructure    22
FMCG              21
Telecom           15
Diversified       14
Energy            13
Cement            12
NBFC              11
Paints            10
Consumer Goods     9
Name: count, dtype: int64

In [4]:
# Step 5: Check portfolio weights by mutual fund

weight_summary = (
    holdings_df.groupby("amfi_code")
    .agg(
        holdings_count=("stock_symbol", "count"),
        total_weight_pct=("weight_pct", "sum"),
        total_market_value_cr=("market_value_cr", "sum"),
    )
    .round(2)
    .sort_values("total_weight_pct", ascending=False)
)

print("Portfolio summary by AMFI code:")
display(weight_summary)

print("\nSummary of total portfolio weights:")
display(weight_summary["total_weight_pct"].describe())

print("\nFunds with total weights above 100%:")
display(weight_summary[weight_summary["total_weight_pct"] > 100])

Portfolio summary by AMFI code:

           holdings_count  total_weight_pct  total_market_value_cr
amfi_code
120505                  8            100.02                4869.31
118632                  8            100.02                8614.35
120506                  9            100.02                9865.87
120841                 10            100.01               13663.82
120504                 11            100.01               12844.50
101206                 10            100.01                9685.28
119552                 11            100.01                8183.78
119094                  9            100.01               10147.79
102887                 10            100.01               11535.15
100016                 10            100.00                6620.93
100033                  9            100.00                7583.03
119093                 10            100.00                8468.55
120503                  8            100.00                9624.29
119599                  8            100.00               10438.59
119551                 10            100.00                5717.74
118634                 10            100.00                9750.09
118633                 11            100.00               11787.88
102885                  9            100.00                7309.01
149323                  9            100.00                8756.37
125498                  8            100.00                8861.56
149324                 12            100.00               14581.81
125497                  8            100.00                6981.70
120843                 10            100.00               11130.85
118635                  8             99.99                9182.91
101207                  8             99.99                6446.71
119095                 11             99.99               10203.15
148568                  8             99.99                7787.69
119598                 12             99.99               13184.81
119092                 10             99.99               10958.50
120842                 10             99.99               11311.93
149322                  9             99.99                8573.92
148567                  8             99.99               11502.67
102886                 11             99.98               11520.60
148569                  9             99.98                7153.48

Summary of total portfolio weights:

count     34.000000
mean      99.999706
std        0.010294
min       99.980000
25%       99.990000
50%      100.000000
75%      100.007500
max      100.020000
Name: total_weight_pct, dtype: float64

Funds with total weights above 100%:

           holdings_count  total_weight_pct  total_market_value_cr
amfi_code
120505                  8            100.02                4869.31
118632                  8            100.02                8614.35
120506                  9            100.02                9865.87
120841                 10            100.01               13663.82
120504                 11            100.01               12844.50
101206                 10            100.01                9685.28
119552                 11            100.01                8183.78
119094                  9            100.01               10147.79
102887                 10            100.01               11535.15

In [5]:
# Step 6: Check duplicate holdings within each fund

holding_key = [
    "amfi_code",
    "stock_symbol",
    "portfolio_date",
]

duplicate_holdings = holdings_df[
    holdings_df.duplicated(subset=holding_key, keep=False)
].sort_values(holding_key)

print("Duplicate fund-stock-date records:", len(duplicate_holdings))

if duplicate_holdings.empty:
    print("No duplicate fund-stock-date records found.")
else:
    display(duplicate_holdings)

print("\nUnique funds:", holdings_df["amfi_code"].nunique())
print("Unique stock symbols:", holdings_df["stock_symbol"].nunique())
print("Total records:", len(holdings_df))

Duplicate fund-stock-date records: 0
No duplicate fund-stock-date records found.

Unique funds: 34
Unique stock symbols: 30
Total records: 322

In [6]:
# Step 7: Standardize text fields and portfolio dates

# Standardize column names
holdings_df.columns = (
    holdings_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Remove leading and trailing whitespace from text fields
text_columns = holdings_df.select_dtypes(include="str").columns

for col in text_columns:
    holdings_df[col] = holdings_df[col].str.strip()

# Convert portfolio_date to datetime
holdings_df["portfolio_date"] = pd.to_datetime(
    holdings_df["portfolio_date"],
    errors="raise"
)

# Verify
print("Dataset shape:", holdings_df.shape)
print("Portfolio date dtype:", holdings_df["portfolio_date"].dtype)
print("Missing values:", holdings_df.isna().sum().sum())
print("Duplicate rows:", holdings_df.duplicated().sum())

print("\nFirst 5 rows:")
display(holdings_df.head())

Dataset shape: (322, 8)
Portfolio date dtype: datetime64[us]
Missing values: 0
Duplicate rows: 0

First 5 rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [7]:
# Step 8: Inspect numeric values and portfolio dates

print("Missing values by column:")
print(holdings_df.isna().sum())

print("\nNumeric summary:")
display(
    holdings_df[
        [
            "weight_pct",
            "market_value_cr",
            "current_price_inr",
        ]
    ].describe().round(2)
)

print("\nLast 5 records:")
display(holdings_df.tail())

print("\nPortfolio dates:")
print(holdings_df["portfolio_date"].value_counts())

Missing values by column:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Numeric summary:

       weight_pct  market_value_cr  current_price_inr
count      322.00           322.00             322.00
mean        10.56          1008.85            4080.87
std          6.06           543.83            2265.19
min          0.99            55.74             246.78
25%          6.02           513.70            2081.98
50%          9.40          1045.67            4139.00
75%         13.92          1477.50            5914.31
max         38.18          1999.50            7942.96

Last 5 records:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
317,149324,DIVISLAB,Divi's Laboratories,Pharma,9.54,855.88,7453.05,2025-12-31
318,149324,BHARTIARTL,Bharti Airtel Ltd,Telecom,1.79,969.71,924.41,2025-12-31
319,149324,TCS,Tata Consultancy Services,IT,13.17,1637.69,1927.89,2025-12-31
320,149324,INDUSINDBK,IndusInd Bank Ltd,Banking,7.63,1387.30,3208.86,2025-12-31
321,149324,NTPC,NTPC Ltd,Utilities,2.04,1303.55,5797.95,2025-12-31

Portfolio dates:
portfolio_date
2025-12-31    322
Name: count, dtype: int64

In [8]:
# Step 9: Export cleaned portfolio holdings

from pathlib import Path

project_path = Path.cwd().parent
processed_folder = project_path / "data" / "processed"
processed_folder.mkdir(parents=True, exist_ok=True)

output_file = (
    processed_folder / "cleaned_portfolio_holdings.csv"
)

holdings_df.to_csv(output_file, index=False)

print("Dataset exported successfully!")
print("Saved to:", output_file)
print("Rows exported:", len(holdings_df))
print("Columns exported:", len(holdings_df.columns))
print("File size (KB):", round(output_file.stat().st_size / 1024, 2))

Dataset exported successfully!
Saved to: d:\Mutual-Fund-Analytics\data\processed\cleaned_portfolio_holdings.csv
Rows exported: 322
Columns exported: 8
File size (KB): 23.66

In [9]:
# Step 10: Verify exported portfolio holdings

verified_df = pd.read_csv(output_file)

print("EXPORTED FILE VERIFICATION")
print("-" * 35)

print("Rows:", verified_df.shape[0])
print("Columns:", verified_df.shape[1])
print("Missing values:", verified_df.isna().sum().sum())
print("Duplicate rows:", verified_df.duplicated().sum())

print("\nColumn names:")
print(verified_df.columns.tolist())

print("\nPortfolio dates:")
print(verified_df["portfolio_date"].value_counts())

print("\nFirst 5 rows:")
display(verified_df.head())

EXPORTED FILE VERIFICATION
-----------------------------------
Rows: 322
Columns: 8
Missing values: 0
Duplicate rows: 0

Column names:
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

Portfolio dates:
portfolio_date
2025-12-31    322
Name: count, dtype: int64

First 5 rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

# Dataset 9: Portfolio Holdings — Cleaning Summary

## Dataset Overview

* **Source file:** `09_portfolio_holdings.csv`
* **Cleaned file:** `cleaned_portfolio_holdings.csv`
* **Original and final dimensions:** 322 rows × 8 columns
* **Portfolio date:** December 31, 2025

## Cleaning and Validation Performed

* Standardized column names to lowercase and snake_case.
* Removed leading and trailing whitespace from text fields.
* Converted `portfolio_date` to datetime format.
* Checked missing values, empty text fields, and duplicate rows.
* Validated positive portfolio weights, market values, and stock prices.
* Checked portfolio weights grouped by AMFI code.
* Checked for duplicate fund-stock-date combinations.
* Exported the cleaned CSV without an additional index column.
* Reloaded the exported file for verification.

## Final Data Quality Results

* Missing values: 0
* Empty text values: 0
* Duplicate rows: 0
* Duplicate fund-stock-date combinations: 0
* Invalid portfolio dates: 0
* Non-positive portfolio weights: 0
* Non-positive market values: 0
* Non-positive stock prices: 0

## Portfolio Weight Analysis

* Unique mutual funds: 34
* Unique stock symbols: 30
* Average portfolio weight per fund: approximately 100%
* Minimum total portfolio weight: 99.98%
* Maximum total portfolio weight: 100.02%

Small differences in total portfolio weights are consistent with rounding. Original values were preserved.

## Conclusion

The portfolio holdings dataset passed the performed data-quality checks and was exported for subsequent analysis. No records were removed, and original financial values were preserved.